# Tensors are the keystone of pytorch

This notbook is inspired from the official pytorch website at the following link: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

---
## <span style="color:red">Tensors</span>

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing. 

In [3]:
import torch
import numpy as np

---
## <span style="color:red">Tensor Initialization</span>

---
### Directly from data:

Tensors can be created directly from data. The data type is automatically inferred.

In [4]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [55]:
print("Type of data =", type(data))
print("Length of data =", len(data))
print(f"data = \n {data} \n")
print("")
print("Type of x_data =", type(x_data))
print("Length of x_data =", len(x_data))
print("Size of x_data =", x_data.shape)
print(f"x_data = \n {x_data} \n")

Type of data = <class 'list'>
Length of data = 2
data = 
 [[1, 2], [3, 4]] 


Type of x_data = <class 'torch.Tensor'>
Length of x_data = 2
Size of x_data = torch.Size([2, 2])
x_data = 
 tensor([[1, 2],
        [3, 4]]) 



---
### From a NumPy array:

Tensors can be created from NumPy arrays (and vice versa)

In [32]:
# np_array = np.array(data) # equivalent to np.array([[1,2],[3,4]])
np_array = np.array([[1,2],[3,4]])  # equivalent to np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [54]:
print("Type of np_array =", type(np_array))
print("Size of data =", np_array.shape)
print(f"np_array = \n {np_array} \n")
print("")
print("Type of x_np =", type(x_np))
print("Size of x_np =", x_np.shape)
print(f"x_n = \n {x_np} \n")

Type of np_array = <class 'numpy.ndarray'>
Size of data = (2, 2)
np_array = 
 [[1 2]
 [3 4]] 


Type of x_np = <class 'torch.Tensor'>
Size of x_np = torch.Size([2, 2])
x_n = 
 tensor([[1, 2],
        [3, 4]]) 



---
### From another tensor:

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [34]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [35]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.5746, 0.8111],
        [0.5329, 0.0621]]) 



---
### With random or constant values:

shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [42]:
shape = (2, 3,)
print("Type of shape =", type(shape))
print("Size of shape =", len(shape))
print(shape)

Type of shape = <class 'tuple'>
Size of shape = 2
(2, 3)


In [43]:
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6980, 0.6079, 0.2294],
        [0.5536, 0.4875, 0.0545]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


---
## <span style="color:red">Tensor Attributes</span>

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [53]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


---
## <span style="color:red">Tensor Operations</span>

Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described [here](https://pytorch.org/docs/stable/torch.html)

Each of them can be run on the GPU (at typically higher speeds than on a CPU).

In [56]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

---
### Standard numpy-like indexing and slicing:

In [58]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(f"tensor =\n {tensor} \n")

tensor =
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



---
### Joining tensors

You can use torch.cat to concatenate a sequence of tensors along a given dimension. See also torch.stack, another tensor joining operator that is subtly different from torch.cat.

In [59]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(f"t1 =\n {t1} \n")

t1 =
 tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]) 



---
### Mutliplying tensors

---
This computes the element-wise product

In [61]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


---
This computes the matrix multiplication between two tensors

In [62]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


---
### In-place operations

Operations that have a _ suffix are in-place, this means that it modifies the tensor in place, without creating a new tensor. In other words, the operation changes the values of the tensor directly, without allocating any additional memory.

In [64]:
print(f"tensor =\n {tensor} \n")
tensor.add_(5)
print(f"tensor =\n {tensor} \n")

tensor =
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor =
 tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 



> **_In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged._**

---
## <span style="color:red">Bridge with numpy</span>
---

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

---
### Tensor to NumPy array

In [66]:
t = torch.ones(5)
print(f"t: \n{t} \n")
n = t.numpy()
print(f"n: \n {n} \n")

t: 
tensor([1., 1., 1., 1., 1.]) 

n: 
 [1. 1. 1. 1. 1.] 



---
A change in the tensor reflects in the NumPy array.

In [67]:
t.add_(1)
print(f"t: \n{t} \n")
print(f"n: \n {n} \n")

t: 
tensor([2., 2., 2., 2., 2.]) 

n: 
 [2. 2. 2. 2. 2.] 



---
### NumPy array to Tensor

In [69]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"n: \n {n} \n")
print(f"t: \n{t} \n")

n: 
 [1. 1. 1. 1. 1.] 

t: 
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) 



---
Changes in the NumPy array reflects in the tensor.

In [71]:
np.add(n, 1, out=n)
print(f"n: \n {n} \n")
print(f"t: \n{t} \n")

n: 
 [3. 3. 3. 3. 3.] 

t: 
tensor([3., 3., 3., 3., 3.], dtype=torch.float64) 



---
### NumPy array to Tensor without shared memory

In [72]:
n = np.ones(5)
t = torch.from_numpy(n.copy())
print(f"n: \n {n} \n")
print(f"t: \n{t} \n")

np.add(n, 1, out=n)
print(f"n: \n {n} \n")
print(f"t: \n{t} \n")

n: 
 [1. 1. 1. 1. 1.] 

t: 
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) 

n: 
 [2. 2. 2. 2. 2.] 

t: 
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) 

